#!/bin/sh

scp sc2015@swancon-mel1.swancon.com.au:/home/sc2015/SwanconRails/staging/shared/db/staging.sqlite3 db/development.sqlite3
rsync -avz --delete sc2015@swancon-mel1.swancon.com.au:/home/sc2015/SwanconRails/staging/shared/public/system/attachments/staging/ public/system/attachments/development
